// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAspNetCore9.Session02.Infrastructure.Data.EF.SqlServer.Data;

#nullable disable

namespace ProAspNetCore9.Session02.Infrastructure.Data.EF.SqlServer.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    [Migration("20261001153429_MakeDueDateNullable")]
    partial class MakeDueDateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Practice manual routing and HttpContext",
                            DueDate = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Status = 0,
                            Title = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 29, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Practice DbContext and repository",
                            DueDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Status = 1,
                            Title = "Learn EF Core"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test endpoint using Postman",
                            DueDate = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Status = 0,
                            Title = "Test GET endpoint"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Review architecture and dependencies",
                            DueDate = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Status = 2,
                            Title = "Refactor Task Management"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This task does not have a due date",
                            IsDeleted = false,
                            Status = 0,
                            Title = "Task without due date"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
